-- tests/bindings/test_lua_binding.lua
--
-- Busted tests for the Insight7 Lua binding.
--
-- Run with:
--   cd build && ~/.luarocks/bin/busted ../../tests/bindings/test_lua_binding.lua
--
-- Note: Uses native _insight module directly to avoid wrapper issues.

-- Adjust paths for busted runner
local build_dir = arg[0]:match("(.*/)") or "./"
package.cpath = build_dir .. "bindings/lua/?.so;" .. package.cpath
package.path = build_dir .. "bindings/lua/?.lua;" .. build_dir .. "bindings/lua/?/init.lua;" .. package.path

local ins = require("_insight")

describe("Insight Lua Binding", function()
  -- =========================================================================
  -- DType
  -- =========================================================================
  describe("DType shortcuts", function()
    it("has float32", function()
      assert.is_not_nil(ins.float32)
    end)
    it("has float64", function()
      assert.is_not_nil(ins.float64)
    end)
    it("has int32", function()
      assert.is_not_nil(ins.int32)
    end)
    it("has int64", function()
      assert.is_not_nil(ins.int64)
    end)
    it("has bool", function()
      assert.is_not_nil(ins.bool)
    end)
    it("has complex64", function()
      assert.is_not_nil(ins.complex64)
    end)
  end)

  -- =========================================================================
  -- Place
  -- =========================================================================
  describe("Place", function()
    it("CPUPlace is_cpu", function()
      local cpu = ins.CPUPlace()
      assert.is_true(cpu:is_cpu())
      assert.is_false(cpu:is_gpu())
    end)
  end)

  -- =========================================================================
  -- Array creation
  -- =========================================================================
  describe("Array creation", function()
    it("zeros", function()
      local a = ins.zeros({ 2, 3 }, ins.float32)
      assert.is_true(a.defined)
      assert.equals(6, a.numel)
    end)
    it("ones", function()
      local a = ins.ones({ 4 }, ins.float64)
      assert.is_true(a.defined)
      assert.equals(4, a.numel)
    end)
    it("full", function()
      local a = ins.full({ 2, 2 }, 3.14, ins.float32)
      assert.is_true(a.defined)
      assert.equals(4, a.numel)
    end)
    it("eye", function()
      local a = ins.eye(3)
      assert.is_true(a.defined)
      assert.equals(9, a.numel)
    end)
    it("arange", function()
      local a = ins.arange(10)
      assert.is_true(a.defined)
      assert.equals(10, a.numel)
    end)
    it("linspace", function()
      local a = ins.linspace(0.0, 1.0, 5)
      assert.is_true(a.defined)
      assert.equals(5, a.numel)
    end)
  end)

  -- =========================================================================
  -- Array properties
  -- =========================================================================
  describe("Array properties", function()
    it("ndim", function()
      local a = ins.zeros({ 2, 3, 4 })
      assert.equals(3, a.ndim)
    end)
    it("numel", function()
      local a = ins.zeros({ 2, 3, 4 })
      assert.equals(24, a.numel)
    end)
  end)

  -- =========================================================================
  -- Arithmetic operators
  -- =========================================================================
  describe("Arithmetic operators", function()
    it("add", function()
      local a = ins.ones({ 3 }, ins.float32)
      local b = ins.ones({ 3 }, ins.float32)
      local c = a + b
      assert.is_true(c.defined)
      assert.equals(3, c.numel)
    end)
    it("sub", function()
      local a = ins.ones({ 3 }, ins.float32)
      local b = ins.ones({ 3 }, ins.float32)
      local c = a - b
      assert.is_true(c.defined)
    end)
    it("mul", function()
      local a = ins.ones({ 3 }, ins.float32)
      local b = ins.ones({ 3 }, ins.float32)
      local c = a * b
      assert.is_true(c.defined)
    end)
    it("div", function()
      local a = ins.ones({ 3 }, ins.float32)
      local b = ins.ones({ 3 }, ins.float32)
      local c = a / b
      assert.is_true(c.defined)
    end)
    it("neg", function()
      local a = ins.ones({ 3 }, ins.float32)
      local c = -a
      assert.is_true(c.defined)
    end)
  end)

  -- =========================================================================
  -- Elementwise functions
  -- =========================================================================
  describe("Elementwise", function()
    it("exp", function()
      local a = ins.ones({ 3 }, ins.float32)
      local b = ins.exp(a)
      assert.is_true(b.defined)
    end)
    it("sin", function()
      local a = ins.ones({ 3 }, ins.float32)
      local b = ins.sin(a)
      assert.is_true(b.defined)
    end)
    it("cos", function()
      local a = ins.ones({ 3 }, ins.float32)
      local b = ins.cos(a)
      assert.is_true(b.defined)
    end)
    it("sqrt", function()
      local a = ins.ones({ 3 }, ins.float32)
      local b = ins.sqrt(a)
      assert.is_true(b.defined)
    end)
    it("abs", function()
      local a = ins.ones({ 3 }, ins.float32)
      local b = ins.abs(a)
      assert.is_true(b.defined)
    end)
    it("log", function()
      local a = ins.ones({ 3 }, ins.float32)
      local b = ins.log(a)
      assert.is_true(b.defined)
    end)
  end)

  -- =========================================================================
  -- Reduction
  -- =========================================================================
  describe("Reduction", function()
    it("sum", function()
      local a = ins.ones({ 3, 4 }, ins.float32)
      local b = ins.sum(a)
      assert.is_true(b.defined)
      assert.equals(1, b.numel)
    end)
    it("mean", function()
      local a = ins.ones({ 3, 4 }, ins.float32)
      local b = ins.mean(a)
      assert.is_true(b.defined)
    end)
    it("max", function()
      local a = ins.ones({ 3, 4 }, ins.float32)
      local b = ins.max(a)
      assert.is_true(b.defined)
    end)
    it("min", function()
      local a = ins.ones({ 3, 4 }, ins.float32)
      local b = ins.min(a)
      assert.is_true(b.defined)
    end)
  end)

  -- =========================================================================
  -- Linear Algebra
  -- =========================================================================
  describe("Linear Algebra", function()
    it("matmul", function()
      local a = ins.ones({ 2, 3 }, ins.float32)
      local b = ins.ones({ 3, 4 }, ins.float32)
      local c = ins.matmul(a, b)
      assert.is_true(c.defined)
      assert.equals(8, c.numel)
    end)
    it("det", function()
      local a = ins.eye(3)
      local d = ins.det(a)
      assert.is_true(d.defined)
    end)
    it("inv", function()
      local a = ins.eye(3)
      local b = ins.inv(a)
      assert.is_true(b.defined)
    end)
    it("trace", function()
      local a = ins.eye(3)
      local t = ins.trace(a)
      assert.is_true(t.defined)
    end)
  end)

  -- =========================================================================
  -- FFT
  -- =========================================================================
  describe("FFT", function()
    it("fft", function()
      local a = ins.ones({ 8 }, ins.float64)
      local b = ins.fft(a)
      assert.is_true(b.defined)
    end)
    it("ifft", function()
      local a = ins.ones({ 8 }, ins.float64)
      local b = ins.fft(a)
      local c = ins.ifft(b)
      assert.is_true(c.defined)
    end)
    it("fftfreq", function()
      local f = ins.fftfreq(8, 1.0)
      assert.is_true(f.defined)
      assert.equals(8, f.numel)
    end)
  end)

  -- =========================================================================
  -- Signal (top-level)
  -- =========================================================================
  describe("Signal (top-level)", function()
    it("convolve exists", function()
      assert.is_not_nil(ins.convolve)
    end)
    it("unwrap exists", function()
      assert.is_not_nil(ins.unwrap)
    end)
    it("sinc exists", function()
      assert.is_not_nil(ins.sinc)
    end)
  end)

  -- =========================================================================
  -- Signal submodule
  -- =========================================================================
  describe("Signal submodule", function()
    it("signal table exists", function()
      assert.is_not_nil(ins.signal)
      assert.equals("table", type(ins.signal))
    end)

    -- Windows
    it("hann exists", function()
      assert.is_not_nil(ins.signal.hann)
    end)
    it("hamming exists", function()
      assert.is_not_nil(ins.signal.hamming)
    end)
    it("blackman exists", function()
      assert.is_not_nil(ins.signal.blackman)
    end)
    it("kaiser exists", function()
      assert.is_not_nil(ins.signal.kaiser)
    end)
    it("gaussian exists", function()
      assert.is_not_nil(ins.signal.gaussian)
    end)
    it("boxcar exists", function()
      assert.is_not_nil(ins.signal.boxcar)
    end)
    it("triang exists", function()
      assert.is_not_nil(ins.signal.triang)
    end)
    it("bartlett exists", function()
      assert.is_not_nil(ins.signal.bartlett)
    end)
    it("flattop exists", function()
      assert.is_not_nil(ins.signal.flattop)
    end)
    it("nuttall exists", function()
      assert.is_not_nil(ins.signal.nuttall)
    end)
    it("blackmanharris exists", function()
      assert.is_not_nil(ins.signal.blackmanharris)
    end)
    it("tukey exists", function()
      assert.is_not_nil(ins.signal.tukey)
    end)
    it("chebwin exists", function()
      assert.is_not_nil(ins.signal.chebwin)
    end)
    it("taylor exists", function()
      assert.is_not_nil(ins.signal.taylor)
    end)
    it("get_window exists", function()
      assert.is_not_nil(ins.signal.get_window)
    end)

    -- Waveforms
    it("sawtooth exists", function()
      assert.is_not_nil(ins.signal.sawtooth)
    end)
    it("square exists", function()
      assert.is_not_nil(ins.signal.square)
    end)
    it("chirp exists", function()
      assert.is_not_nil(ins.signal.chirp)
    end)
    it("unit_impulse exists", function()
      assert.is_not_nil(ins.signal.unit_impulse)
    end)

    -- B-Splines
    it("gauss_spline exists", function()
      assert.is_not_nil(ins.signal.gauss_spline)
    end)
    it("cubic exists", function()
      assert.is_not_nil(ins.signal.cubic)
    end)
    it("quadratic exists", function()
      assert.is_not_nil(ins.signal.quadratic)
    end)

    -- Filter Design
    it("kaiser_beta exists", function()
      assert.is_not_nil(ins.signal.kaiser_beta)
    end)
    it("kaiser_atten exists", function()
      assert.is_not_nil(ins.signal.kaiser_atten)
    end)
    it("firwin exists", function()
      assert.is_not_nil(ins.signal.firwin)
    end)
    it("firwin2 exists", function()
      assert.is_not_nil(ins.signal.firwin2)
    end)
    it("cmplx_sort exists", function()
      assert.is_not_nil(ins.signal.cmplx_sort)
    end)

    -- Convolution
    it("fftconvolve exists", function()
      assert.is_not_nil(ins.signal.fftconvolve)
    end)
    it("correlate exists", function()
      assert.is_not_nil(ins.signal.correlate)
    end)
    it("convolve2d exists", function()
      assert.is_not_nil(ins.signal.convolve2d)
    end)
    it("correlate2d exists", function()
      assert.is_not_nil(ins.signal.correlate2d)
    end)
    it("choose_conv_method exists", function()
      assert.is_not_nil(ins.signal.choose_conv_method)
    end)
    it("correlation_lags exists", function()
      assert.is_not_nil(ins.signal.correlation_lags)
    end)

    -- Filtering
    it("hilbert exists", function()
      assert.is_not_nil(ins.signal.hilbert)
    end)
    it("hilbert2 exists", function()
      assert.is_not_nil(ins.signal.hilbert2)
    end)
    it("detrend exists", function()
      assert.is_not_nil(ins.signal.detrend)
    end)
    it("wiener exists", function()
      assert.is_not_nil(ins.signal.wiener)
    end)
    it("firfilter exists", function()
      assert.is_not_nil(ins.signal.firfilter)
    end)
    it("lfilter exists", function()
      assert.is_not_nil(ins.signal.lfilter)
    end)
    it("lfilter_zi exists", function()
      assert.is_not_nil(ins.signal.lfilter_zi)
    end)
    it("filtfilt exists", function()
      assert.is_not_nil(ins.signal.filtfilt)
    end)
    it("decimate exists", function()
      assert.is_not_nil(ins.signal.decimate)
    end)
    it("resample exists", function()
      assert.is_not_nil(ins.signal.resample)
    end)
    it("resample_poly exists", function()
      assert.is_not_nil(ins.signal.resample_poly)
    end)
    it("freq_shift exists", function()
      assert.is_not_nil(ins.signal.freq_shift)
    end)

    -- Spectral Analysis
    it("welch exists", function()
      assert.is_not_nil(ins.signal.welch)
    end)
    it("periodogram exists", function()
      assert.is_not_nil(ins.signal.periodogram)
    end)
    it("csd exists", function()
      assert.is_not_nil(ins.signal.csd)
    end)
    it("coherence exists", function()
      assert.is_not_nil(ins.signal.coherence)
    end)
    it("spectrogram exists", function()
      assert.is_not_nil(ins.signal.spectrogram)
    end)
    it("stft exists", function()
      assert.is_not_nil(ins.signal.stft)
    end)
    it("vectorstrength exists", function()
      assert.is_not_nil(ins.signal.vectorstrength)
    end)

    -- Wavelets
    it("morlet exists", function()
      assert.is_not_nil(ins.signal.morlet)
    end)
    it("ricker exists", function()
      assert.is_not_nil(ins.signal.ricker)
    end)
    it("morlet2 exists", function()
      assert.is_not_nil(ins.signal.morlet2)
    end)

    -- Acoustics
    it("mel2hz exists", function()
      assert.is_not_nil(ins.signal.mel2hz)
    end)
    it("hz2mel exists", function()
      assert.is_not_nil(ins.signal.hz2mel)
    end)
    it("mel_frequencies exists", function()
      assert.is_not_nil(ins.signal.mel_frequencies)
    end)
    it("hz2bark exists", function()
      assert.is_not_nil(ins.signal.hz2bark)
    end)
    it("bark2hz exists", function()
      assert.is_not_nil(ins.signal.bark2hz)
    end)

    -- ChirpMethod enum
    it("ChirpMethod enum exists", function()
      assert.is_not_nil(ins.signal.ChirpMethod)
      assert.is_not_nil(ins.signal.ChirpMethod.linear)
      assert.is_not_nil(ins.signal.ChirpMethod.quadratic)
      assert.is_not_nil(ins.signal.ChirpMethod.logarithmic)
      assert.is_not_nil(ins.signal.ChirpMethod.hyperbolic)
    end)

    -- Scalar-returning functions
    it("kaiser_beta returns number", function()
      local beta = ins.signal.kaiser_beta(50)
      assert.equals("number", type(beta))
      assert.is_true(beta > 0)
    end)
    it("kaiser_atten returns number", function()
      local atten = ins.signal.kaiser_atten(100, 0.1)
      assert.equals("number", type(atten))
    end)

    -- Phase 2+3: Demod
    it("fm_demod exists", function()
      assert.is_not_nil(ins.signal.fm_demod)
    end)

    -- Phase 2+3: Peak Finding
    it("argrelextrema exists", function()
      assert.is_not_nil(ins.signal.argrelextrema)
    end)
    it("argrelmax exists", function()
      assert.is_not_nil(ins.signal.argrelmax)
    end)
    it("argrelmin exists", function()
      assert.is_not_nil(ins.signal.argrelmin)
    end)

    -- Phase 2+3: Radar
    it("pulse_compression exists", function()
      assert.is_not_nil(ins.signal.pulse_compression)
    end)
    it("pulse_doppler exists", function()
      assert.is_not_nil(ins.signal.pulse_doppler)
    end)
    it("cfar_alpha returns number", function()
      local alpha = ins.signal.cfar_alpha(1e-3, 20)
      assert.equals("number", type(alpha))
      assert.is_true(alpha > 0)
    end)
    it("ca_cfar exists", function()
      assert.is_not_nil(ins.signal.ca_cfar)
    end)
    it("mvdr exists", function()
      assert.is_not_nil(ins.signal.mvdr)
    end)
    it("ambgfun exists", function()
      assert.is_not_nil(ins.signal.ambgfun)
    end)

    -- Phase 2+3: Estimation
    it("KalmanFilter exists", function()
      assert.is_not_nil(ins.signal.KalmanFilter)
    end)

    -- Phase 2+3: Signal I/O
    it("read_bin exists", function()
      assert.is_not_nil(ins.signal.read_bin)
    end)
    it("write_bin exists", function()
      assert.is_not_nil(ins.signal.write_bin)
    end)
    it("unpack_bin exists", function()
      assert.is_not_nil(ins.signal.unpack_bin)
    end)
    it("pack_bin exists", function()
      assert.is_not_nil(ins.signal.pack_bin)
    end)
    it("read_sigmf exists", function()
      assert.is_not_nil(ins.signal.read_sigmf)
    end)
    it("write_sigmf exists", function()
      assert.is_not_nil(ins.signal.write_sigmf)
    end)
  end)

  -- =========================================================================
  -- Plot submodule
  -- =========================================================================
  describe("Plot submodule", function()
    it("plot table exists", function()
      assert.is_not_nil(ins.plot)
      assert.equals("table", type(ins.plot))
    end)
    it("figure exists", function()
      assert.is_not_nil(ins.plot.figure)
    end)
    it("plot exists", function()
      assert.is_not_nil(ins.plot.plot)
    end)
    it("scatter exists", function()
      assert.is_not_nil(ins.plot.scatter)
    end)
    it("bar exists", function()
      assert.is_not_nil(ins.plot.bar)
    end)
    it("hist exists", function()
      assert.is_not_nil(ins.plot.hist)
    end)
    it("title exists", function()
      assert.is_not_nil(ins.plot.title)
    end)
    it("xlabel exists", function()
      assert.is_not_nil(ins.plot.xlabel)
    end)
    it("show exists", function()
      assert.is_not_nil(ins.plot.show)
    end)
    it("save exists", function()
      assert.is_not_nil(ins.plot.save)
    end)
    it("surf exists", function()
      assert.is_not_nil(ins.plot.surf)
    end)
    it("contour exists", function()
      assert.is_not_nil(ins.plot.contour)
    end)
  end)

  -- =========================================================================
  -- Complex (Phase D)
  -- =========================================================================
  describe("Complex", function()
    it("is_complex exists", function()
      assert.is_not_nil(ins.is_complex)
    end)
    it("has_complex_shape exists", function()
      assert.is_not_nil(ins.has_complex_shape)
    end)
    it("to_complex single arg", function()
      local a = ins.ones({ 3 }, ins.float32)
      local c = ins.to_complex(a)
      assert.is_not_nil(c)
      assert.is_true(ins.is_complex(c))
    end)
    it("to_complex two args", function()
      local r = ins.ones({ 3 }, ins.float32)
      local i = ins.zeros({ 3 }, ins.float32)
      local c = ins.to_complex(r, i)
      assert.is_not_nil(c)
    end)
    it("as_complex exists", function()
      assert.is_not_nil(ins.as_complex)
    end)
    it("as_real exists", function()
      assert.is_not_nil(ins.as_real)
    end)
    it("real and imag", function()
      assert.is_not_nil(ins.real)
      assert.is_not_nil(ins.imag)
    end)
  end)

  -- =========================================================================
  -- Additional Unary (Phase D)
  -- =========================================================================
  describe("Additional Unary", function()
    local a = ins.linspace(0.1, 2.0, 10, ins.float32)
    it("exp2", function()
      local r = ins.exp2(a)
      assert.is_not_nil(r)
      assert.equals(10, r.numel)
    end)
    it("expm1", function()
      local r = ins.expm1(a)
      assert.is_not_nil(r)
    end)
    it("log1p", function()
      local r = ins.log1p(a)
      assert.is_not_nil(r)
    end)
    it("cbrt", function()
      local r = ins.cbrt(a)
      assert.is_not_nil(r)
    end)
    it("reciprocal", function()
      local r = ins.reciprocal(a)
      assert.is_not_nil(r)
    end)
    it("asinh", function()
      local r = ins.asinh(a)
      assert.is_not_nil(r)
    end)
    it("acosh", function()
      local r = ins.acosh(a)
      assert.is_not_nil(r)
    end)
    it("atanh", function()
      local small = ins.linspace(0.1, 0.9, 5, ins.float32)
      local r = ins.atanh(small)
      assert.is_not_nil(r)
    end)
    it("trunc", function()
      local r = ins.trunc(a)
      assert.is_not_nil(r)
    end)
    it("deg2rad", function()
      local r = ins.deg2rad(a)
      assert.is_not_nil(r)
    end)
    it("rad2deg", function()
      local r = ins.rad2deg(a)
      assert.is_not_nil(r)
    end)
  end)

  -- =========================================================================
  -- Additional Reduction (Phase D)
  -- =========================================================================
  describe("Additional Reduction", function()
    local a = ins.from_table({ { 1, 2, 3 }, { 4, 5, 6 } })
    it("cummax", function()
      local r = ins.cummax(a, 0)
      assert.is_not_nil(r)
    end)
    it("cummin", function()
      local r = ins.cummin(a, 0)
      assert.is_not_nil(r)
    end)
    it("count_nonzero", function()
      local r = ins.count_nonzero(a)
      assert.is_not_nil(r)
    end)
    it("median", function()
      local r = ins.median(a)
      assert.is_not_nil(r)
    end)
    it("quantile scalar", function()
      local r = ins.quantile(a, 0.5)
      assert.is_not_nil(r)
    end)
    it("percentile", function()
      local r = ins.percentile(a, 50.0)
      assert.is_not_nil(r)
    end)
    it("nansum", function()
      local r = ins.nansum(a)
      assert.is_not_nil(r)
    end)
    it("nanmean", function()
      local r = ins.nanmean(a)
      assert.is_not_nil(r)
    end)
    it("nanmax", function()
      local r = ins.nanmax(a)
      assert.is_not_nil(r)
    end)
    it("nanmin", function()
      local r = ins.nanmin(a)
      assert.is_not_nil(r)
    end)
    it("nanstd", function()
      local r = ins.nanstd(a)
      assert.is_not_nil(r)
    end)
    it("nanvar", function()
      local r = ins.nanvar(a)
      assert.is_not_nil(r)
    end)
  end)

  -- =========================================================================
  -- Additional Manipulation (Phase D)
  -- =========================================================================
  describe("Additional Manipulation", function()
    local a = ins.from_table({ { 1, 2, 3 }, { 4, 5, 6 } })
    it("permute", function()
      local r = ins.permute(a, { 1, 0 })
      assert.is_not_nil(r)
      assert.equals(3, r.shape[1])
      assert.equals(2, r.shape[2])
    end)
    it("swapaxes", function()
      local r = ins.swapaxes(a, 0, 1)
      assert.is_not_nil(r)
    end)
    it("moveaxis", function()
      local r = ins.moveaxis(a, 0, 1)
      assert.is_not_nil(r)
    end)
    it("fliplr", function()
      local r = ins.fliplr(a)
      assert.is_not_nil(r)
    end)
    it("flipud", function()
      local r = ins.flipud(a)
      assert.is_not_nil(r)
    end)
    it("rot90", function()
      local r = ins.rot90(a)
      assert.is_not_nil(r)
    end)
    it("diag square matrix", function()
      local m = ins.eye(3)
      local r = ins.diag(m)
      assert.is_not_nil(r)
      assert.equals(3, r.numel)
    end)
    it("diagonal", function()
      local r = ins.diagonal(a)
      assert.is_not_nil(r)
    end)
    it("tril", function()
      local r = ins.tril(a)
      assert.is_not_nil(r)
    end)
    it("triu", function()
      local r = ins.triu(a)
      assert.is_not_nil(r)
    end)
    it("diff", function()
      local r = ins.diff(a)
      assert.is_not_nil(r)
    end)
  end)

  -- =========================================================================
  -- Additional Indexing (Phase D)
  -- =========================================================================
  describe("Additional Indexing", function()
    it("UniqueResult usertype", function()
      assert.is_not_nil(ins.UniqueResult)
    end)
    it("unique", function()
      local a = ins.from_table({ 1, 2, 2, 3, 3, 3 })
      local r = ins.unique(a)
      assert.is_not_nil(r)
      assert.is_not_nil(r.unique)
      assert.equals(3, r.unique.numel)
    end)
    it("unique with counts", function()
      local a = ins.from_table({ 1, 2, 2, 3, 3, 3 })
      local r = ins.unique(a, false, false, true)
      assert.is_not_nil(r.counts)
    end)
    it("topk", function()
      local a = ins.from_table({ 1, 5, 3, 4, 2 })
      local vals, idx = ins.topk(a, 3)
      assert.is_not_nil(vals)
      assert.is_not_nil(idx)
      assert.equals(3, vals.numel)
    end)
    it("gather", function()
      local a = ins.from_table({ 10, 20, 30, 40, 50 })
      local idx = ins.from_table({ 0, 2, 4 }):to(ins.int64)
      local r = ins.gather(a, 0, idx)
      assert.is_not_nil(r)
      assert.equals(3, r.numel)
    end)
    it("interp", function()
      local x = ins.from_table({ 1.5, 2.5 })
      local xp = ins.from_table({ 1, 2, 3 })
      local fp = ins.from_table({ 10, 20, 30 })
      local r = ins.interp(x, xp, fp)
      assert.is_not_nil(r)
      assert.equals(2, r.numel)
    end)
    it("indices", function()
      local r = ins.indices(ins.Shape({ 2, 3 }))
      assert.is_not_nil(r)
    end)
  end)

  -- =========================================================================
  -- Additional Random (Phase D)
  -- =========================================================================
  describe("Additional Random", function()
    it("seed", function()
      assert.is_not_nil(ins.seed)
      ins.seed(42)
    end)
    it("get_seed", function()
      local s = ins.get_seed()
      assert.is_number(s)
    end)
    it("rand_like", function()
      local a = ins.zeros({ 3, 4 }, ins.float32)
      local r = ins.rand_like(a)
      assert.is_not_nil(r)
      assert.equals(12, r.numel)
    end)
    it("randn_like", function()
      local a = ins.zeros({ 3, 4 }, ins.float32)
      local r = ins.randn_like(a)
      assert.is_not_nil(r)
    end)
    it("exponential", function()
      local r = ins.exponential(1.0, { 3, 4 })
      assert.is_not_nil(r)
      assert.equals(12, r.numel)
    end)
    it("gamma", function()
      local r = ins.gamma(2.0, 1.0, { 3, 4 })
      assert.is_not_nil(r)
    end)
    it("beta", function()
      local r = ins.beta(2.0, 5.0, { 3, 4 })
      assert.is_not_nil(r)
    end)
    it("binomial", function()
      local r = ins.binomial(10, 0.5, { 3, 4 })
      assert.is_not_nil(r)
    end)
    it("poisson", function()
      local r = ins.poisson(3.0, { 3, 4 })
      assert.is_not_nil(r)
    end)
  end)

  -- =========================================================================
  -- Additional FFT (Phase D)
  -- =========================================================================
  describe("Additional FFT", function()
    it("fftshift", function()
      local a = ins.arange(0, 8, 1, ins.float32)
      local r = ins.fftshift(a)
      assert.is_not_nil(r)
      assert.equals(8, r.numel)
    end)
    it("ifftshift", function()
      local a = ins.arange(0, 8, 1, ins.float32)
      local r = ins.ifftshift(a)
      assert.is_not_nil(r)
    end)
    it("next_fast_len", function()
      local r = ins.next_fast_len(100)
      assert.is_number(r)
      assert.is_true(r >= 100)
    end)
    it("hfft", function()
      local a = ins.ones({ 8 }, ins.float32)
      local c = ins.to_complex(a)
      local r = ins.hfft(c)
      assert.is_not_nil(r)
      assert.is_true(r.numel > 0)
    end)
    it("ihfft", function()
      -- ihfft takes real input, returns complex
      local a = ins.ones({ 8 }, ins.float32)
      local r = ins.ihfft(a)
      assert.is_not_nil(r)
      assert.is_true(r.numel > 0)
    end)
  end)

  -- =========================================================================
  -- Device Info
  -- =========================================================================
  describe("Device Info", function()
    it("device_name cpu", function()
      local name = ins.device_name("cpu")
      assert.equals("CPU", name)
    end)
    it("cuda_version returns number", function()
      local v = ins.cuda_version()
      assert.is_number(v)
    end)
    it("driver_version returns number", function()
      local v = ins.driver_version()
      assert.is_number(v)
    end)
    it("compute_capability returns number", function()
      local v = ins.compute_capability()
      assert.is_number(v)
    end)
    it("device_memory returns two values", function()
      local total, free = ins.device_memory()
      assert.is_number(total)
      assert.is_number(free)
    end)
    it("gpu_count returns number", function()
      local c = ins.gpu_count()
      assert.is_number(c)
    end)
  end)

  -- =========================================================================
  -- GPU (load_backend + GPUPlace)
  -- =========================================================================
  describe("GPU", function()
    it("load_backend exists", function()
      assert.is_not_nil(ins.load_backend)
    end)
    it("GPUPlace exists", function()
      assert.is_not_nil(ins.GPUPlace)
    end)
    it("load_backend cuda", function()
      assert.has_no.errors(function()
        ins.load_backend("cuda")
      end)
    end)
    it("GPUPlace creation", function()
      local gpu = ins.GPUPlace(0)
      assert.is_true(gpu:is_gpu())
      assert.is_false(gpu:is_cpu())
    end)
    it("device_name gpu after load", function()
      local name = ins.device_name("gpu", 0)
      assert.is_not_nil(name)
      assert.is_true(#name > 0)
    end)
    it("array to GPU", function()
      local a = ins.ones({ 3, 4 }, ins.float32)
      local gpu = ins.GPUPlace(0)
      local b = a:to(gpu)
      assert.is_true(b.place:is_gpu())
      assert.equals(12, b.numel)
    end)
    it("array GPU roundtrip", function()
      local a = ins.from_table({ 1, 2, 3, 4 })
      local gpu = ins.GPUPlace(0)
      local b = a:to(gpu)
      local c = b:to(ins.CPUPlace())
      assert.equals(4, c.numel)
    end)
  end)
end)
