-- CPU basic operations tests — aligned with C++ test suite
-- Run with:
--   LUA_PATH="bindings/lua/?/init.lua;;" LUA_CPATH="build/bindings/lua/?.so;;" \
--   LD_LIBRARY_PATH=build/backends/cpu ~/.luarocks/bin/busted tests/cpu/lua/test_cpu_basic.lua

describe("CreationTestCPU", function()
    local ins
    setup(function()
        ins = require("_insight")
    end)

    it("zeros", function()
        local a = ins.zeros({2, 3}, ins.float32)
        assert.is_not_nil(a)
        assert.are.equal(6, a.numel)
    end)

    it("ones", function()
        local a = ins.ones({2, 3}, ins.float32)
        assert.is_not_nil(a)
        assert.are.equal(6, a.numel)
    end)

    it("full", function()
        local a = ins.full({2, 3}, 3.14, ins.float32)
        assert.is_not_nil(a)
        assert.are.equal(6, a.numel)
    end)

    it("eye", function()
        local a = ins.eye(3)
        assert.is_not_nil(a)
        assert.are.equal(9, a.numel)
    end)

    it("arange", function()
        local a = ins.arange(10, ins.float32)
        assert.is_not_nil(a)
        assert.are.equal(10, a.numel)
    end)

    it("linspace", function()
        local a = ins.linspace(0.0, 1.0, 5, ins.float32)
        assert.is_not_nil(a)
        assert.are.equal(5, a.numel)
    end)
end)

describe("ElementwiseTestCPU", function()
    local ins
    setup(function()
        ins = require("_insight")
    end)

    it("add", function()
        local a = ins.from_table({1, 2, 3})
        local b = ins.from_table({4, 5, 6})
        local c = ins.add(a, b)
        assert.is_not_nil(c)
        assert.are.equal(3, c.numel)
    end)

    it("sub", function()
        local a = ins.from_table({10, 20, 30})
        local b = ins.from_table({1, 2, 3})
        local c = ins.sub(a, b)
        assert.is_not_nil(c)
        assert.are.equal(3, c.numel)
    end)

    it("mul", function()
        local a = ins.from_table({2, 3, 4})
        local b = ins.from_table({5, 6, 7})
        local c = ins.mul(a, b)
        assert.is_not_nil(c)
        assert.are.equal(3, c.numel)
    end)

    it("div", function()
        local a = ins.from_table({10, 20, 30})
        local b = ins.from_table({2, 4, 5})
        local c = ins.div(a, b)
        assert.is_not_nil(c)
        assert.are.equal(3, c.numel)
    end)
end)

describe("UnaryTestCPU", function()
    local ins
    setup(function()
        ins = require("_insight")
    end)

    it("abs", function()
        local a = ins.from_table({-3, -1, 0, 2, 4})
        local b = ins.abs(a)
        assert.is_not_nil(b)
        assert.are.equal(5, b.numel)
    end)

    it("sqrt", function()
        local a = ins.from_table({1, 4, 9, 16})
        local b = ins.sqrt(a)
        assert.is_not_nil(b)
        assert.are.equal(4, b.numel)
    end)

    it("exp", function()
        local a = ins.from_table({0, 1, 2})
        local b = ins.exp(a)
        assert.is_not_nil(b)
        assert.are.equal(3, b.numel)
    end)

    it("sin", function()
        local a = ins.from_table({0, 0.5, 1.0})
        local b = ins.sin(a)
        assert.is_not_nil(b)
        assert.are.equal(3, b.numel)
    end)
end)

describe("ReductionTestCPU", function()
    local ins
    setup(function()
        ins = require("_insight")
    end)

    it("sum", function()
        local a = ins.from_table({1, 2, 3, 4})
        local s = ins.sum(a)
        assert.is_not_nil(s)
        assert.are.equal(1, s.numel)
    end)

    it("mean", function()
        local a = ins.from_table({1, 2, 3, 4})
        local m = ins.mean(a)
        assert.is_not_nil(m)
        assert.are.equal(1, m.numel)
    end)

    it("max", function()
        local a = ins.from_table({3, 1, 4, 1, 5})
        local m = ins.max(a)
        assert.is_not_nil(m)
    end)

    it("min", function()
        local a = ins.from_table({3, 1, 4, 1, 5})
        local m = ins.min(a)
        assert.is_not_nil(m)
    end)
end)

describe("LinalgTestCPU", function()
    local ins
    setup(function()
        ins = require("_insight")
    end)

    it("matmul", function()
        local a = ins.from_table({{1, 2}, {3, 4}})
        local b = ins.from_table({{5, 6}, {7, 8}})
        local c = ins.matmul(a, b)
        assert.is_not_nil(c)
        assert.are.equal(4, c.numel)
    end)

    it("det", function()
        local a = ins.from_table({{1, 2}, {3, 4}})
        local d = ins.det(a)
        assert.is_not_nil(d)
    end)

    it("inv", function()
        local a = ins.from_table({{1, 2}, {3, 4}})
        local b = ins.inv(a)
        assert.is_not_nil(b)
        assert.are.equal(4, b.numel)
    end)

    it("trace", function()
        local a = ins.from_table({{1, 2}, {3, 4}})
        local t = ins.trace(a)
        assert.is_not_nil(t)
    end)
end)

describe("FFTTestCPU", function()
    local ins
    setup(function()
        ins = require("_insight")
    end)

    it("fft", function()
        local x = ins.from_table({1, 2, 3, 4})
        local y = ins.fft(x)
        assert.is_not_nil(y)
        assert.are.equal(4, y.numel)
    end)

    it("ifft", function()
        local x = ins.from_table({1, 2, 3, 4})
        local y = ins.fft(x)
        local z = ins.ifft(y)
        assert.is_not_nil(z)
        assert.are.equal(4, z.numel)
    end)

    it("fftfreq", function()
        local f = ins.fftfreq(8, 1.0)
        assert.is_not_nil(f)
        assert.are.equal(8, f.numel)
    end)
end)

describe("SignalTestCPU", function()
    local ins
    setup(function()
        ins = require("_insight")
    end)

    it("hann window", function()
        local w = ins.signal.hann(16)
        assert.is_not_nil(w)
        assert.are.equal(16, w.numel)
    end)

    it("hamming window", function()
        local w = ins.signal.hamming(16)
        assert.is_not_nil(w)
        assert.are.equal(16, w.numel)
    end)

    it("blackman window", function()
        local w = ins.signal.blackman(32)
        assert.is_not_nil(w)
        assert.are.equal(32, w.numel)
    end)

    it("fftconvolve", function()
        local a = ins.from_table({1, 2, 3})
        local b = ins.from_table({1, 1})
        local c = ins.signal.fftconvolve(a, b)
        assert.is_not_nil(c)
    end)
end)
