-- Complex number CPU binding tests
-- Run with:
--   LUA_PATH="bindings/lua/?/init.lua;;" LUA_CPATH="build/bindings/lua/?.so;;" \
--   LD_LIBRARY_PATH=build/backends/cpu ~/.luarocks/bin/busted tests/cpu/lua/test_complex.lua

describe("Complex CPU Tests", function()
  local ins
  setup(function()
    ins = require("_insight")
  end)

  it("is_complex on real array", function()
    local a = ins.from_table({ 1.0, 2.0, 3.0 })
    assert.is_falsy(ins.is_complex(a))
  end)

  it("to_complex", function()
    local real = ins.from_table({ 1.0, 2.0, 3.0 })
    local c = ins.to_complex(real)
    assert.is_not_nil(c)
    assert.are.equal(3, c.numel)
  end)

  it("to_complex with imag", function()
    local real = ins.from_table({ 1.0, 2.0, 3.0 })
    local imag = ins.from_table({ 4.0, 5.0, 6.0 })
    local c = ins.to_complex(real, imag)
    assert.is_not_nil(c)
    assert.are.equal(3, c.numel)
  end)

  it("real part", function()
    local real = ins.from_table({ 1.0, 2.0, 3.0 })
    local c = ins.to_complex(real)
    local r = ins.real(c)
    assert.is_not_nil(r)
    assert.are.equal(3, r.numel)
  end)

  it("imag part", function()
    local real = ins.from_table({ 1.0, 2.0, 3.0 })
    local c = ins.to_complex(real)
    local i = ins.imag(c)
    assert.is_not_nil(i)
    assert.are.equal(3, i.numel)
  end)

  it("as_complex", function()
    local a = ins.from_table({ 1.0, 2.0, 3.0, 4.0 })
    a = a:reshape({ 2, 2 })
    local c = ins.as_complex(a)
    assert.is_not_nil(c)
  end)

  it("as_real", function()
    local real = ins.from_table({ 1.0, 2.0, 3.0, 4.0 })
    a = real:reshape({ 2, 2 })
    local c = ins.as_complex(a)
    local r = ins.as_real(c)
    assert.is_not_nil(r)
    assert.are.equal(4, r.numel)
  end)

  it("has_complex_shape", function()
    local a = ins.from_table({ 1.0, 2.0, 3.0, 4.0 })
    a = a:reshape({ 2, 2 })
    assert.is_truthy(ins.has_complex_shape(a))
  end)

  it("complex abs", function()
    local real = ins.from_table({ 1.0, 2.0 })
    local c = ins.to_complex(real)
    local a = ins.abs(c)
    assert.is_not_nil(a)
    assert.are.equal(2, a.numel)
  end)

  it("complex conj", function()
    pending("conj is not exposed in Lua binding")
  end)

  it("complex angle", function()
    pending("angle is not exposed in Lua binding")
  end)

  it("complex add", function()
    local real1 = ins.from_table({ 1.0, 2.0 })
    local c1 = ins.to_complex(real1)
    local real2 = ins.from_table({ 3.0, 4.0 })
    local c2 = ins.to_complex(real2)
    local s = ins.add(c1, c2)
    assert.is_not_nil(s)
    assert.are.equal(2, s.numel)
  end)

  it("complex mul", function()
    local real1 = ins.from_table({ 1.0, 2.0 })
    local c1 = ins.to_complex(real1)
    local real2 = ins.from_table({ 3.0, 4.0 })
    local c2 = ins.to_complex(real2)
    local p = ins.mul(c1, c2)
    assert.is_not_nil(p)
    assert.are.equal(2, p.numel)
  end)

  it("real exp", function()
    local a = ins.from_table({ 0.0, 1.0, 2.0 })
    local e = ins.exp(a)
    assert.is_not_nil(e)
    assert.are.equal(3, e.numel)
  end)

  it("as_complex as_real roundtrip", function()
    local a = ins.from_table({ 1.0, 2.0, 3.0, 4.0 })
    a = a:reshape({ 2, 2 })
    local c = ins.as_complex(a)
    local r = ins.as_real(c)
    assert.is_not_nil(r)
    assert.are.equal(4, r.numel)
  end)
end)
